server:
  port: 80
  error:
    whitelabel:
      enabled: false

spring:
  output:
    ansi:
      enabled: always
  # 视图配置
  thymeleaf:
     cache: false
     prefix: classpath:templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
