server:
  port: 80
#  context-path: /root

spring:
  output:
    ansi:
      enabled: detect # 日志颜色
  # 视图配置
  thymeleaf:
     cache: false
     prefix: classpath:templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
